services:
  bot:
    build: .
    container_name: ryangosling-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    volumes:
      - .:/usr/src/app
    command: [ "node", "index.js" ]
